'use client';

import React, { useState, useMemo, useRef } from 'react';
import { useChecklists } from '@/lib/hooks/use-checklists';
import { useRestaurantStore } from '@/lib/store/restaurant-store';
import { useRouter, useSearchParams } from 'next/navigation';
import { useCreateExecucao, useTurnoAtual } from '@/lib/hooks/use-execucoes';
import { uploadEvidencePhoto } from '@/lib/supabase/storage';
import Link from 'next/link';

export default function TarefaDetailsPage({ params }: { params: Promise<{ id: string }> }) {
    const { id } = React.use(params);
    const searchParams = useSearchParams();
    const checklistId = searchParams.get('c');

    const router = useRouter();
    const { restaurantId } = useRestaurantStore();
    const { data: checklists, isLoading } = useChecklists(restaurantId || undefined);
    const { data: execucoes } = useTurnoAtual(restaurantId || null);
    const { mutateAsync: createExecution, isPending } = useCreateExecucao();

    // Verifica se esta tarefa já foi executada hoje
    const alreadyDoneToday = !!(execucoes as Array<{ task_id: string; status: string }> | null | undefined)
        ?.find(e => e.task_id === id && e.status === 'done');

    const [isUploading, setIsUploading] = useState(false);
    const [file, setFile] = useState<File | null>(null);
    const [previewUrl, setPreviewUrl] = useState<string | null>(null);
    const fileInputRef = useRef<HTMLInputElement>(null);

    // Report Issue states
    const [isReportModalOpen, setIsReportModalOpen] = useState(false);
    const [reportNotes, setReportNotes] = useState('');
    const [isReporting, setIsReporting] = useState(false);

    const taskData = useMemo(() => {
        if (!checklists || !id || !checklistId) return null;
        const cl = checklists.find(c => c.id === checklistId);
        if (!cl) return null;
        const task = cl.tasks?.find(t => t.id === id);
        return task ? { ...task, checklist: cl } : null;
    }, [checklists, id, checklistId]);

    const isBlockedSequential = useMemo(() => {
        if (!taskData || !taskData.checklist.enforce_sequential_order) return false;
        
        const tasks = taskData.checklist.tasks || [];
        const sortedTasks = [...tasks].sort((a,b) => (a.order ?? 0) - (b.order ?? 0));
        const currentIndex = sortedTasks.findIndex(t => t.id === id);
        
        if (currentIndex > 0) {
            const prevTask = sortedTasks[currentIndex - 1];
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            const prevDone = !!(execucoes as any[])?.find(e => e.task_id === prevTask.id && e.status === 'done');
            if (!prevDone) return true;
        }
        return false;
    }, [taskData, execucoes, id]);

    if (isLoading) {
        return (
            <div className="flex h-screen items-center justify-center bg-[#f6f8f8] dark:bg-[#101d22]">
                <div className="animate-spin text-primary">
                    <span className="material-symbols-outlined text-4xl">refresh</span>
                </div>
            </div>
        );
    }

    if (!taskData) {
        return (
            <div className="p-6 text-center text-red-500">
                Tarefa não encontrada ou restrita.
            </div>
        );
    }

    const { checklist, title, description, is_critical } = taskData;
    const isReadyToSubmit = is_critical ? !!file : true;

    const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const selectedFile = e.target.files?.[0];
        if (!selectedFile) return;
        if (!['image/jpeg', 'image/png'].includes(selectedFile.type)) {
            alert('Por favor, envie apenas imagens JPG ou PNG.');
            return;
        }

        setFile(selectedFile);
        const objectUrl = URL.createObjectURL(selectedFile);
        setPreviewUrl(objectUrl);
    };

    const handleSubmit = async () => {
        if (is_critical && !file) {
            alert('Esta é uma tarefa crítica e exige foto-evidência preenchida.');
            return;
        }

        setIsUploading(true);

        try {
            let photoPath = '';

            // Cria log (provisório ou faz de vez e salva o ID)
            // Em nosso fluxo POST podemos mandar o photoPath antes

            if (file && restaurantId) {
                // The execution ID is generated by backend typically, but we need photoPath.
                // We can generate a UUID beforehand or use task_id + timestamp.
                const tempId = crypto.randomUUID();
                photoPath = await uploadEvidencePhoto(file, restaurantId, tempId);
            }

            const res = await createExecution({
                task_id: id,
                checklist_id: checklistId!,
                restaurant_id: restaurantId!,
                status: 'done',
                notes: '',
                photo_url: photoPath
            });

            router.push(`/turno/tarefa/${res.id}/confirmacao`);
        } catch (e: unknown) {
            console.error('[Submit Tarefa Erro]:', e);
            alert((e as Error).message || 'Houve um erro indesejado ao concluir. Tente novamente.');
        } finally {
            setIsUploading(false);
        }
    };

    const handleReportIssue = async () => {
        if (!reportNotes.trim()) {
            alert('Por favor, descreva o problema.');
            return;
        }

        setIsReporting(true);
        try {
            await createExecution({
                task_id: id,
                checklist_id: checklistId!,
                restaurant_id: restaurantId!,
                status: 'flagged',
                notes: reportNotes,
                photo_url: ''
            });

            setIsReportModalOpen(false);
            setReportNotes('');
            alert('Problema reportado com sucesso!'); // Feedback visual provisório (toast fake)
            router.push('/turno'); // Volta ao painel pós report
        } catch (e: unknown) {
            console.error('[Submit Report Erro]:', e);
            alert((e as Error).message || 'Houve um erro ao enviar o relatório.');
        } finally {
            setIsReporting(false);
        }
    };

    return (
        <div className="min-h-screen bg-[#f6f8f8] dark:bg-[#101d22] font-display text-slate-900 dark:text-white pb-24 mx-auto max-w-[500px] w-full flex flex-col">
            <header className="px-4 py-4 border-b border-gray-200 dark:border-[#233f48] bg-white dark:bg-[#111e22] sticky top-0 z-30">
                <Link href="/turno" className="flex items-center gap-2 text-slate-500 hover:text-primary transition-colors">
                    <span className="material-symbols-outlined text-[20px]">arrow_back_ios_new</span>
                    <span className="text-sm font-semibold uppercase tracking-wider">Voltar ao Turno</span>
                </Link>
            </header>

            <main className="flex-1 p-6 flex flex-col gap-6">
                <div>
                    {is_critical && (
                        <span className="inline-flex items-center gap-1 mb-3 px-2 py-1 rounded-sm bg-amber-100 dark:bg-amber-900/30 text-amber-600 dark:text-amber-400 text-xs font-bold uppercase tracking-wider">
                            <span className="material-symbols-outlined text-[14px]">warning</span> Crítico
                        </span>
                    )}
                    <h1 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-white mb-2 leading-tight">
                        {title}
                    </h1>
                    <p className="text-sm font-medium text-slate-500 dark:text-[#92bbc9]">
                        Pertencente à: <span className="text-primary">{checklist.name}</span>
                    </p>
                </div>

                <div className="bg-white dark:bg-[#16262c] rounded-xl p-5 border border-gray-200 dark:border-[#233f48] shadow-sm">
                    <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-[#92bbc9] mb-3">Instruções</h3>
                    <p className="text-sm text-slate-700 dark:text-white whitespace-pre-wrap leading-relaxed">
                        {description || 'Sem instruções adicionais para esta tarefa.'}
                    </p>
                </div>

                {/* Bloco de Foto */}
                {is_critical && (
                    <div className="flex flex-col gap-3">
                        <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-[#92bbc9]">Evidência Obrigatória</h3>

                        <div
                            onClick={() => fileInputRef.current?.click()}
                            className="w-full aspect-video rounded-xl bg-gray-50 dark:bg-[#111e22] border-2 border-dashed border-gray-300 dark:border-[#233f48] hover:border-primary dark:hover:border-primary transition-colors flex flex-col items-center justify-center cursor-pointer relative overflow-hidden group"
                        >
                            <input
                                type="file"
                                accept="image/png, image/jpeg"
                                ref={fileInputRef}
                                className="hidden"
                                onChange={handleFileChange}
                            />

                            {previewUrl ? (
                                <div className="absolute inset-0 w-full h-full">
                                    {/* eslint-disable-next-line @next/next/no-img-element */}
                                    <img src={previewUrl} alt="Preview da Foto" className="w-full h-full object-cover" />
                                    <div className="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                                        <p className="text-white font-medium text-sm flex gap-2 items-center">
                                            <span className="material-symbols-outlined">cameraswitch</span>
                                            Trocar Imagem
                                        </p>
                                    </div>
                                </div>
                            ) : (
                                <div className="flex flex-col gap-2 items-center text-slate-400 dark:text-[#92bbc9] group-hover:text-primary transition-colors">
                                    <span className="material-symbols-outlined text-4xl">add_a_photo</span>
                                    <p className="text-sm font-medium">Toque para anexar foto</p>
                                </div>
                            )}
                        </div>
                    </div>
                )}
            </main>

            {/* Ações Inferiores Padrão App nativo (Fixas bottom) */}
            <div className="fixed bottom-0 left-0 right-0 w-full bg-white dark:bg-[#111e22] border-t border-gray-200 dark:border-[#233f48] p-6 flex flex-col gap-3 max-w-[500px] mx-auto z-40 pb-safe">
                <button
                    onClick={handleSubmit}
                    disabled={!isReadyToSubmit || isPending || isUploading || alreadyDoneToday || isBlockedSequential}
                    className="w-full bg-primary hover:bg-primary/90 disabled:opacity-50 disabled:cursor-not-allowed text-[#111e22] text-lg font-bold py-4 rounded-xl shadow-lg shadow-primary/20 transition-all flex items-center justify-center gap-2"
                >
                    {isBlockedSequential ? (
                        <>
                            <span className="material-symbols-outlined text-[24px]">lock</span>
                            Conclua a tarefa anterior primeiro
                        </>
                    ) : alreadyDoneToday ? (
                        <>
                            <span className="material-symbols-outlined text-[24px]">task_alt</span>
                            Já concluída hoje
                        </>
                    ) : (isUploading || isPending) ? (
                        <>
                            <span className="material-symbols-outlined animate-spin text-[20px]">refresh</span>
                            Enviando...
                        </>
                    ) : (
                        <>
                            <span className="material-symbols-outlined text-[24px]">task_alt</span>
                            Concluir Tarefa
                        </>
                    )}
                </button>
                <button
                    onClick={() => setIsReportModalOpen(true)}
                    className="w-full bg-transparent hover:bg-gray-50 dark:hover:bg-white/5 text-slate-500 dark:text-[#92bbc9] hover:text-slate-700 dark:hover:text-white text-base font-medium py-3 rounded-xl transition-colors flex items-center justify-center gap-2"
                >
                    <span className="material-symbols-outlined text-[20px]">report</span>
                    Reportar Problema
                </button>
            </div>

            {/* Modal de Report */}
            {isReportModalOpen && (
                <div className="fixed inset-0 bg-black/80 z-50 flex items-center justify-center p-4">
                    <div className="bg-[#16262c] border border-[#233f48] rounded-2xl w-full max-w-sm p-6 shadow-2xl animate-fade-in flex flex-col gap-4">
                        <div className="flex items-center gap-3 text-white">
                            <span className="material-symbols-outlined text-amber-500">warning</span>
                            <h3 className="text-xl font-bold tracking-tight">Reportar um problema</h3>
                        </div>

                        <textarea
                            className="w-full bg-[#101d22] border border-[#233f48] rounded-xl p-4 text-white text-sm focus:border-amber-500 focus:ring-1 focus:ring-amber-500 outline-none transition-all placeholder:text-[#325a67] resize-none"
                            rows={4}
                            placeholder="Descreva o problema encontrado..."
                            value={reportNotes}
                            onChange={(e) => setReportNotes(e.target.value)}
                        />

                        <div className="flex gap-3 justify-end mt-2">
                            <button
                                onClick={() => setIsReportModalOpen(false)}
                                disabled={isReporting}
                                className="px-4 py-2 rounded-lg font-bold text-sm text-[#92bbc9] hover:bg-[#1a2c32] hover:text-white transition-colors"
                            >
                                Cancelar
                            </button>
                            <button
                                onClick={handleReportIssue}
                                disabled={isReporting || !reportNotes.trim()}
                                className="px-4 py-2 rounded-lg font-bold text-sm bg-amber-500/10 text-amber-500 border border-amber-500/30 hover:bg-amber-500 hover:text-[#111e22] transition-colors disabled:opacity-50 flex items-center justify-center"
                            >
                                {isReporting ? (
                                    <span className="material-symbols-outlined animate-spin text-[18px]">refresh</span>
                                ) : "Enviar Relatório"}
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
