-- ============================================================
-- Sprint 72 — Seed dos 6 Kits (conteúdo)
-- ============================================================
-- Idempotente: kits por slug; itens por (kit_id, template_id).
-- Composição = Core comum (obrigatório/recomendado) + delta por segmento.
-- Obrigatório = modo Essencial (padrão do 1-clique).
-- Recomendado = modo Completo. Opcional = avulso no preview.
-- ============================================================

BEGIN;

INSERT INTO public.template_kits (slug, name, description, segment, icon, sort_order)
VALUES
  ('kit-restaurante', 'Kit Restaurante',
   'Operação completa para restaurante à la carte / casual: cozinha, salão, caixa e segurança alimentar.',
   'restaurante', 'restaurant', 10),
  ('kit-hamburgueria', 'Kit Hamburgueria',
   'Rotinas para hamburgueria: chapa, fritura, delivery e segurança alimentar.',
   'hamburgueria', 'lunch_dining', 20),
  ('kit-pizzaria', 'Kit Pizzaria',
   'Rotinas para pizzaria: forno, pré-preparo, delivery e câmara fria.',
   'pizzaria', 'local_pizza', 30),
  ('kit-cafeteria', 'Kit Cafeteria',
   'Rotinas para cafeteria: balcão, validade, higiene e manutenção de equipamentos.',
   'cafeteria', 'local_cafe', 40),
  ('kit-fast-food', 'Kit Fast Food',
   'Rotinas para fast food: alto volume, padronização, fritura e expedição.',
   'fast_food', 'fastfood', 50),
  ('kit-gastrobar', 'Kit Gastrobar',
   'Rotinas para gastrobar: cozinha + bar, atendimento e controle de perdas.',
   'gastrobar', 'sports_bar', 60)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description, segment = EXCLUDED.segment,
  icon = EXCLUDED.icon, sort_order = EXCLUDED.sort_order, updated_at = now();

-- Composição (kit_slug, template_slug, requirement_level, sort_order)
INSERT INTO public.template_kit_items (kit_id, template_id, requirement_level, sort_order)
SELECT k.id, ct.id, v.level, v.ord
FROM (VALUES
  -- ===== KIT RESTAURANTE =====
  ('kit-restaurante','abertura-cozinha','obrigatorio',1),
  ('kit-restaurante','fechamento-cozinha','obrigatorio',2),
  ('kit-restaurante','abertura-caixa','obrigatorio',3),
  ('kit-restaurante','fechamento-caixa','obrigatorio',4),
  ('kit-restaurante','controle-temperatura','obrigatorio',5),
  ('kit-restaurante','higiene-saude-equipe','obrigatorio',6),
  ('kit-restaurante','controle-validade-etiquetagem','obrigatorio',7),
  ('kit-restaurante','limpeza-geral-fechamento','obrigatorio',8),
  ('kit-restaurante','higienizacao-banheiros','obrigatorio',9),
  ('kit-restaurante','mise-en-place','obrigatorio',10),
  ('kit-restaurante','montagem-mesas','obrigatorio',11),
  ('kit-restaurante','padrao-atendimento','obrigatorio',12),
  ('kit-restaurante','boas-praticas-manipulacao','recomendado',13),
  ('kit-restaurante','plano-limpeza-higienizacao','recomendado',14),
  ('kit-restaurante','fechamento-financeiro-dia','recomendado',15),
  ('kit-restaurante','passagem-turno','recomendado',16),
  ('kit-restaurante','contagem-estoque','recomendado',17),
  ('kit-restaurante','controle-cmv','recomendado',18),
  ('kit-restaurante','abertura-salao','opcional',19),
  ('kit-restaurante','fechamento-salao','opcional',20),
  ('kit-restaurante','organizacao-camara-fria','opcional',21),
  ('kit-restaurante','pedido-compras-reposicao','opcional',22),
  ('kit-restaurante','higienizacao-frutas-verduras','opcional',23),
  ('kit-restaurante','vigilancia-sanitaria','opcional',24),
  ('kit-restaurante','manutencao-preventiva','opcional',25),
  ('kit-restaurante','auditoria-caixa','opcional',26),

  -- ===== KIT HAMBURGUERIA =====
  ('kit-hamburgueria','abertura-cozinha','obrigatorio',1),
  ('kit-hamburgueria','fechamento-cozinha','obrigatorio',2),
  ('kit-hamburgueria','abertura-caixa','obrigatorio',3),
  ('kit-hamburgueria','fechamento-caixa','obrigatorio',4),
  ('kit-hamburgueria','controle-temperatura','obrigatorio',5),
  ('kit-hamburgueria','higiene-saude-equipe','obrigatorio',6),
  ('kit-hamburgueria','controle-validade-etiquetagem','obrigatorio',7),
  ('kit-hamburgueria','limpeza-geral-fechamento','obrigatorio',8),
  ('kit-hamburgueria','higienizacao-banheiros','obrigatorio',9),
  ('kit-hamburgueria','mise-en-place','obrigatorio',10),
  ('kit-hamburgueria','troca-oleo-fritadeiras','obrigatorio',11),
  ('kit-hamburgueria','limpeza-coifa-exaustao','obrigatorio',12),
  ('kit-hamburgueria','boas-praticas-manipulacao','recomendado',13),
  ('kit-hamburgueria','plano-limpeza-higienizacao','recomendado',14),
  ('kit-hamburgueria','fechamento-financeiro-dia','recomendado',15),
  ('kit-hamburgueria','passagem-turno','recomendado',16),
  ('kit-hamburgueria','conferencia-pedidos-delivery','recomendado',17),
  ('kit-hamburgueria','higiene-temperatura-entrega','recomendado',18),
  ('kit-hamburgueria','controle-cmv','recomendado',19),
  ('kit-hamburgueria','padrao-atendimento','opcional',20),
  ('kit-hamburgueria','contagem-estoque','opcional',21),
  ('kit-hamburgueria','pedido-compras-reposicao','opcional',22),
  ('kit-hamburgueria','auditoria-caixa','opcional',23),
  ('kit-hamburgueria','manutencao-preventiva','opcional',24),
  ('kit-hamburgueria','controle-pragas','opcional',25),
  ('kit-hamburgueria','vigilancia-sanitaria','opcional',26),

  -- ===== KIT PIZZARIA =====
  ('kit-pizzaria','abertura-cozinha','obrigatorio',1),
  ('kit-pizzaria','fechamento-cozinha','obrigatorio',2),
  ('kit-pizzaria','abertura-caixa','obrigatorio',3),
  ('kit-pizzaria','fechamento-caixa','obrigatorio',4),
  ('kit-pizzaria','controle-temperatura','obrigatorio',5),
  ('kit-pizzaria','higiene-saude-equipe','obrigatorio',6),
  ('kit-pizzaria','controle-validade-etiquetagem','obrigatorio',7),
  ('kit-pizzaria','limpeza-geral-fechamento','obrigatorio',8),
  ('kit-pizzaria','higienizacao-banheiros','obrigatorio',9),
  ('kit-pizzaria','mise-en-place','obrigatorio',10),
  ('kit-pizzaria','limpeza-coifa-exaustao','obrigatorio',11),
  ('kit-pizzaria','boas-praticas-manipulacao','recomendado',12),
  ('kit-pizzaria','plano-limpeza-higienizacao','recomendado',13),
  ('kit-pizzaria','fechamento-financeiro-dia','recomendado',14),
  ('kit-pizzaria','passagem-turno','recomendado',15),
  ('kit-pizzaria','conferencia-pedidos-delivery','recomendado',16),
  ('kit-pizzaria','higiene-temperatura-entrega','recomendado',17),
  ('kit-pizzaria','organizacao-camara-fria','recomendado',18),
  ('kit-pizzaria','controle-cmv','recomendado',19),
  ('kit-pizzaria','padrao-atendimento','opcional',20),
  ('kit-pizzaria','montagem-mesas','opcional',21),
  ('kit-pizzaria','contagem-estoque','opcional',22),
  ('kit-pizzaria','pedido-compras-reposicao','opcional',23),
  ('kit-pizzaria','manutencao-preventiva','opcional',24),
  ('kit-pizzaria','vigilancia-sanitaria','opcional',25),

  -- ===== KIT CAFETERIA =====
  ('kit-cafeteria','abertura-cozinha','obrigatorio',1),
  ('kit-cafeteria','fechamento-cozinha','obrigatorio',2),
  ('kit-cafeteria','abertura-caixa','obrigatorio',3),
  ('kit-cafeteria','fechamento-caixa','obrigatorio',4),
  ('kit-cafeteria','controle-temperatura','obrigatorio',5),
  ('kit-cafeteria','higiene-saude-equipe','obrigatorio',6),
  ('kit-cafeteria','controle-validade-etiquetagem','obrigatorio',7),
  ('kit-cafeteria','limpeza-geral-fechamento','obrigatorio',8),
  ('kit-cafeteria','higienizacao-banheiros','obrigatorio',9),
  ('kit-cafeteria','boas-praticas-manipulacao','recomendado',10),
  ('kit-cafeteria','plano-limpeza-higienizacao','recomendado',11),
  ('kit-cafeteria','fechamento-financeiro-dia','recomendado',12),
  ('kit-cafeteria','passagem-turno','recomendado',13),
  ('kit-cafeteria','manutencao-preventiva','recomendado',14),
  ('kit-cafeteria','padrao-atendimento','recomendado',15),
  ('kit-cafeteria','mise-en-place','opcional',16),
  ('kit-cafeteria','contagem-estoque','opcional',17),
  ('kit-cafeteria','pedido-compras-reposicao','opcional',18),
  ('kit-cafeteria','conferencia-pedidos-delivery','opcional',19),
  ('kit-cafeteria','controle-cmv','opcional',20),
  ('kit-cafeteria','vigilancia-sanitaria','opcional',21),
  ('kit-cafeteria','higienizacao-frutas-verduras','opcional',22),

  -- ===== KIT FAST FOOD =====
  ('kit-fast-food','abertura-cozinha','obrigatorio',1),
  ('kit-fast-food','fechamento-cozinha','obrigatorio',2),
  ('kit-fast-food','abertura-caixa','obrigatorio',3),
  ('kit-fast-food','fechamento-caixa','obrigatorio',4),
  ('kit-fast-food','controle-temperatura','obrigatorio',5),
  ('kit-fast-food','higiene-saude-equipe','obrigatorio',6),
  ('kit-fast-food','controle-validade-etiquetagem','obrigatorio',7),
  ('kit-fast-food','limpeza-geral-fechamento','obrigatorio',8),
  ('kit-fast-food','higienizacao-banheiros','obrigatorio',9),
  ('kit-fast-food','mise-en-place','obrigatorio',10),
  ('kit-fast-food','troca-oleo-fritadeiras','obrigatorio',11),
  ('kit-fast-food','conferencia-pedidos-delivery','obrigatorio',12),
  ('kit-fast-food','limpeza-coifa-exaustao','obrigatorio',13),
  ('kit-fast-food','boas-praticas-manipulacao','recomendado',14),
  ('kit-fast-food','plano-limpeza-higienizacao','recomendado',15),
  ('kit-fast-food','fechamento-financeiro-dia','recomendado',16),
  ('kit-fast-food','passagem-turno','recomendado',17),
  ('kit-fast-food','higiene-temperatura-entrega','recomendado',18),
  ('kit-fast-food','auditoria-caixa','recomendado',19),
  ('kit-fast-food','controle-cmv','recomendado',20),
  ('kit-fast-food','padrao-atendimento','recomendado',21),
  ('kit-fast-food','contagem-estoque','opcional',22),
  ('kit-fast-food','pedido-compras-reposicao','opcional',23),
  ('kit-fast-food','manutencao-preventiva','opcional',24),
  ('kit-fast-food','controle-pragas','opcional',25),
  ('kit-fast-food','vigilancia-sanitaria','opcional',26),
  ('kit-fast-food','organizacao-camara-fria','opcional',27),

  -- ===== KIT GASTROBAR =====
  ('kit-gastrobar','abertura-cozinha','obrigatorio',1),
  ('kit-gastrobar','fechamento-cozinha','obrigatorio',2),
  ('kit-gastrobar','abertura-caixa','obrigatorio',3),
  ('kit-gastrobar','fechamento-caixa','obrigatorio',4),
  ('kit-gastrobar','controle-temperatura','obrigatorio',5),
  ('kit-gastrobar','higiene-saude-equipe','obrigatorio',6),
  ('kit-gastrobar','controle-validade-etiquetagem','obrigatorio',7),
  ('kit-gastrobar','limpeza-geral-fechamento','obrigatorio',8),
  ('kit-gastrobar','higienizacao-banheiros','obrigatorio',9),
  ('kit-gastrobar','mise-en-place','obrigatorio',10),
  ('kit-gastrobar','padrao-atendimento','obrigatorio',11),
  ('kit-gastrobar','boas-praticas-manipulacao','recomendado',12),
  ('kit-gastrobar','plano-limpeza-higienizacao','recomendado',13),
  ('kit-gastrobar','fechamento-financeiro-dia','recomendado',14),
  ('kit-gastrobar','passagem-turno','recomendado',15),
  ('kit-gastrobar','contagem-estoque','recomendado',16),
  ('kit-gastrobar','controle-cmv','recomendado',17),
  ('kit-gastrobar','auditoria-caixa','recomendado',18),
  ('kit-gastrobar','conferencia-sangria','recomendado',19),
  ('kit-gastrobar','montagem-mesas','recomendado',20),
  ('kit-gastrobar','conferencia-pedidos-delivery','opcional',21),
  ('kit-gastrobar','organizacao-camara-fria','opcional',22),
  ('kit-gastrobar','pedido-compras-reposicao','opcional',23),
  ('kit-gastrobar','manutencao-preventiva','opcional',24),
  ('kit-gastrobar','vigilancia-sanitaria','opcional',25),
  ('kit-gastrobar','higienizacao-frutas-verduras','opcional',26)
) AS v(kit_slug, tpl_slug, level, ord)
JOIN public.template_kits k        ON k.slug  = v.kit_slug
JOIN public.checklist_templates ct ON ct.slug = v.tpl_slug
ON CONFLICT (kit_id, template_id) DO UPDATE SET
  requirement_level = EXCLUDED.requirement_level,
  sort_order        = EXCLUDED.sort_order;

COMMIT;
